language: cpp
compiler:
  - gcc
cache: apt
before_script:
  - sudo mkdir -p /riplet/service
  - sudo ln -s "$(readlink -f .)" /riplet/service/postgres
  - chmod +x /riplet/service/postgres/build
script: sudo /riplet/service/postgres/build
