language: cpp
compiler:
  - gcc
cache: apt
before_script:
  - sudo apt-get -y install daemontools
  - sudo mkdir -p /riplet/service
  - sudo ln -s "$(readlink -f .)" /riplet/service/postgres
  - chmod +x /riplet/service/postgres/build  /riplet/service/postgres/run  /riplet/service/postgres/test
  - sudo /riplet/service/postgres/build
  - sudo -u postgres /usr/lib/postgresql/9.3/bin/pg_ctl -D /data/postgres start
script:
  - echo "Testing"; sudo -u postgres psql -c 'select version();'; echo "Tested"; sudo -u postgres /usr/lib/postgresql/9.3/bin/pg_ctl -D /data/postgres stop
