language: cpp
compiler:
  - gcc
cache: apt
before_script:
  - sudo apt-get -y install daemontools
  - sudo mkdir -p /riplet/service
  - sudo ln -s "$(readlink -f .)" /riplet/service/postgres
  - chmod +x /riplet/service/postgres/build  /riplet/service/postgres/run  /riplet/service/postgres/test
  - sudo /riplet/service/postgres/build
  - sudo /bin/sh -c '/riplet/service/postgres/run &'
script: /riplet/service/postgres/test
