language: cpp
compiler:
  - gcc
cache: apt
before_script:
  - sudo apt-get -y install daemontools
  - sudo mkdir -p /riplet/service
  - sudo ln -s "$(readlink -f .)" /riplet/service/nginx
  - chmod +x /riplet/service/nginx/build  /riplet/service/nginx/init  /riplet/service/nginx/test   /riplet/service/nginx/conf
  - sudo /riplet/service/nginx/build
  - sudo /riplet/service/nginx/conf
  - sudo -u nginx /usr/sbin/nginx start
script:
  - sudo -u nginx /riplet/service/nginx/test
after_script:
  - sudo -u nginx /usr/sbin/nginx stop
