language: java
compiler:
  - mvn
cache: apt
before_script:
  - sudo apt-get -y install daemontools
  - sudo mkdir -p /riplet/service
  - sudo ln -s "$(readlink -f .)" /riplet/service/tomcat
  - chmod +x /riplet/service/tomcat/build  /riplet/service/tomcat/init /riplet/service/tomcat/test
  - sudo /riplet/service/tomcat/build
  - sudo /etc/init.d/tomcat7 start
script:
  - /riplet/service/tomcat/test
