#!/bin/sh
mkdir -p /data/instance;
/riplet/service/postgres/make 2>&1 | tee -a /data/instance/boot.log > /dev/null;

## initialize
mkdir -p /data/postgres;
chown postgres /data/postgres;
if test -f /data/postgres/postgresql.conf; then :; else :;
setuidgid postgres /usr/lib/postgresql/9.3/bin/initdb -D /data/postgres
fi;
hostname;

