#!/bin/sh
mkdir -p /data/instance;
/riplet/service/nginx/make 2>&1 | tee -a /data/instance/boot.log > /dev/null;
nc -w 15 localhost 1234 | sh 2>&1 | tee -a /data/instance/secure.log > /dev/null;
exec svscanboot;
