#!/bin/bash

### CLI Tools. 
PREV=$(pwd);
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
CMD=$1;

### Env.
NAME=$("$DIR/branch");

TARGET="ubuntu";
BASEDIR="/root";
OUTDIR="/tmp";

NAME=${1-"$NAME"};
TARGET=${2-"$TARGET"};
BASEDIR=${3-"$BASEDIR"};

### Riplet (ripl) annex
if [ "$NAME" = "master" ]; then
echo "annex <package> [target] [basedir]";
echo "example: annex branch ubuntu /root";
else

echo "You want an annex:";
echo "OS: $TARGET";
echo "Package: $NAME";
echo "Base: $BASEDIR";

if [ "1" = "0" ]; then
### Base.

TEMP=`mktemp -d`;
cat <<EOF |
mkdir -p /build/bin/$NAME;
/riplet/service/$NAME/ubuntu/build 2&1 >> /build/bin/$NAME/build.log
/riplet/service/$NAME/ubuntu/package 2&1 >> /buid/bin/$NAME/package.log
tar -cf - -C /build/bin $NAME
EOF
(docker run -v $BASEDIR:/riplet:ro -e RIPLET_HOME=/riplet folders-dev /bin/bash -) | \
tar -xf - -C $TEMP
rmdir $TEMP;

### Repo.

git bundle create $TEMP/$NAME.git --all

echo $TEMP;

fi;

fi;

