#!/bin/bash
NAME="$1";
BASEDIR=${2-"/root"};
RIPLET_HOME="/riplet";
RIPLET_INSTANCE="/data/instance";

if [ -n "$1" ]; then
ENTRY="service/$1/init";

if [ -f "$BASEDIR/$ENTRY" ]; then
TEMP=$(mkdir -d);
TEMP_PID="$TEMP/$NAME.docker";
TEMP_RAND=$(</dev/urandom tr -dc _A-Z-a-z-0-9 | head -c32);

echo -n "$TEMP_RAND" > $TEMP/$NAME.random

read -r -d '' RIPLET_DOCKER_CMD <<EOF
docker run
 -n=false -dns 0.0.0.0
 -cidfile $TEMP_PID
 -v $TEMP:$RIPLET_INSTANCE:rw
 -v $BASEDIR:$RIPLET_HOME:ro
 -e RIPLET_HOME=$RIPLET_HOME
 -e RIPLET_INSTANCE=$RIPLET_INSTANCE
-d foldersio-dev $RIPLET_HOME/$ENTRY
EOF

$($RIPLET_DOCKER_CMD)

else
echo "riplet error: Service file not found: $BASEDIR/$ENTRY";
fi;

else
echo "riplet usage: ripl docker <service> [basedir]";
fi;

