#!/bin/bash

### CLI Tools.
PREV=$(pwd);
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
CMD=$1;

### Env.
NAME=$("$DIR/branch");

### Riplet (ripl)

if [ "$NAME" = "master" ]; then

if [ "$CMD" = "ls" ]; then
NAME=${2-"$NAME"};
echo "riplet: $NAME /";
git ls-tree -r --name-only $NAME
elif [ "$CMD" = "all" ]; then
echo "riplet: /";
git branch -a
else
echo "riplet: $NAME /";
git branch -l
fi;


else

if [ "$CMD" = "sh" ]; then
$DIR/sh "$@"

elif [ "$CMD" = "docker" ]; then
$DIR/docker "$@"

elif [ "$CMD" = "image" ]; then
$DIR/image "$@"

else
cat <<E
riplet: $NAME
  sh docker image
  sh: build the package and open a shell
  docker: build the package and run an instance.
  image: build the package and return a container id.

helper: help
  git: replace clone uris fetched via git with annex uris.
  curl: replace http(s) urls fetched via curl with annex uris.
  branch: show the name of the current riplet branch.
E
fi;

fi;

