#!/bin/bash
BASEDIR=${2-"/root"};

if [ -n "$1" ]; then
# ENTRY="service/$1/build";
ENTRY="service/$1/make";
DEPS="/riplet/service/$1/cli/ubuntu/deps";

if [ -f "$BASEDIR/$ENTRY" ]; then
cat <<E
docker run -v $BASEDIR:/riplet:ro -e RIPLET_HOME=/riplet -n=false -dns 0.0.0.0 \
	-t -i foldersio-dev \
	/bin/bash -c "$DEPS && /riplet/$ENTRY && exec /bin/bash"
E
else
echo "riplet error: Service file not found: $BASEDIR/$ENTRY";
fi;

else
cat <<E
# Make then open a bash terminal of a new container.
	ripl sh <service> [basedir]
E
fi;

